// Brian McKenna - SD2B
// External Libaries used: Material UI, Bootstrap, Font Awesome

import React, {Component} from 'react';
import AddMovieModalBox from '../components/Modal/AddMovieModalBox';
import InputBoxes from '../components/InputBoxes/InputBoxes';
import MovieTable from '../components/MovieTable/MovieTable';
import '../scss/styles.scss';

export default class DisplayMovieRecords extends Component
{
    constructor(props) 
    {
        super(props)
        
        this.state = {
            movieData: [],
            search: '',
            countTableSortClick: 0
        } 
    }

    componentDidMount() 
    {
        const movieData = [
            {"Title":"Electric Shadows","Year":"2004","Rated":"N/A","Released":"07 Apr 2005","Runtime":"93 min","Genre":"Drama","Director":"Jiang Xiao","Writer":"ingsong Cheng, Jiang Xiao","Actors":"Yu Xia, Haibin Li, Yijing Zhang, Zhongyang i","Plot":"For no apparent reason, a mute young woman assaults a youth who delivers water on his bicycle, injuring him and ruining his bike. Surprisingly, she asks him to feed her fish while she is in custody. Her tiny apartment, he discovers, is a shrine to his favorite escape, the movies. He finds her diary - a screenplay of her life built around scenes from favorite films - and it sets off his imagination. Maybe they have more in common than a love of the movies.","Language":"Mandarin","Country":"China","Awards":"4 wins & 1 nomination.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjE1NTg5MzY4MV5BMl5BanBnXkFtZTcwMDY5OTMzM@@._V1_SX300.jpg","Metascore":"70","imdbRating":"7.6","imdbVotes":"869","imdbID":"tt0424273","Type":"movie","Response":"True"},
{"Title":"Emergency","Year":"1962","Rated":"N/A","Released":"01 Mar 1962","Runtime":"63 min","Genre":"Drama","Director":"Francis Searle","Writer":"Lewis Gilbert (story), Vernon Harris (story), Don Nicholl (screenplay), Jim O'Connolly (screenplay)","Actors":"Glyn Houston, Zena Walker, Dermot Walsh, Colin Tapley","Plot":"When a little girl is knocked down it is discovered that there are only three donors of the right blood type to help with a life-saving operation. One is a murderer awaiting execution, one ...","Language":"English","Country":"UK","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"5.5","imdbVotes":"24","imdbID":"tt0055955","Type":"movie","Response":"True"},
{"Title":"The Steel Helmet","Year":"1951","Rated":"APPROVED","Released":"02 Feb 1951","Runtime":"85 min","Genre":"Action, Drama, War","Director":"Samuel Fuller","Writer":"Samuel Fuller","Actors":"Gene Evans, Robert Hutton, Steve Brodie, James Edwards","Plot":"During the Korean War, strong but worn and cantankerous Sergeant Zack is aided by a young, orphaned Korean boy. Together they encounter and join a small group of American soldiers. The group stumbles upon a Buddhist temple where they decide to hold up, believing it to be empty...","Language":"English","Country":"USA","Awards":"1 win.","Poster":"http://ia.media-imdb.com/images/M/MV5BNjYwMjwNzY3Ml5BMl5BanBnXkFtZTgwND1OTgwMzE@._V1._CR60,43,218,272_SY132_CR8,0,89,132_AL_.jpg_V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.6","imdbVotes":"2,564","imdbID":"tt0044072","Type":"movie","Response":"True"},
{"Title":"Mama Steps Out","Year":"1937","Rated":"APPROVED","Released":"05 Feb 1937","Runtime":"65 min","Genre":"Comedy, Romance","Director":"George B. Seitz","Writer":"John Alexander Kirkpatrick (play), Anita Loos","Actors":"Guy Kibbee, Alice Brady, Betty Furness, Dennis Morgan","Plot":"After inheriting a fortune, the Cuppy family of Fort Wayne, Indiana go to France to \"broaden\" their cultural outlook...","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMDY4ZWI1MjMtMDdkNi00NzA4LWI3MjctOTYxNmIzYzVmZTA0XkEyXkFcGdeXVyMTIxOTk5MzY@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"6.0","imdbVotes":"99","imdbID":"tt0029196","Type":"movie","Response":"True"},
{"Title":"Grayson","Year":"2004","Rated":"NOT RATED","Released":"20 Jul 2004","Runtime":"6 min","Genre":"Sci-Fi, Short, Action","Director":"John Fiorella","Writer":"John Fiorella, Bob Kane (characters)","Actors":"John Fiorella, Brian C. Bethel, Paul Hasenyager, Anthony Heartley","Plot":"Batman has been murdered and the only man who can uncover the mystery behind his murder is his former partner, Dick Grayson aka Robin! Grayson uncovers a conspiracy the corrupt chief of police conspired with Batmans Rogue's Gallery to kill him and now they've set their sights on, Grayson!","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BNTZiMGwNzYtNGJmNy00YzU1LWJjYmMtYzlhZmRkNDg4NmYxXkEyXkFcGdeXVyNjk3ODk2OA@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.6","imdbVotes":"1,544","imdbID":"tt0430154","Type":"movie","Response":"True"},
{"Title":"Aida","Year":"1953","Rated":"APPROVED","Released":"08 Oct 1954","Runtime":"95 min","Genre":"Musical","Director":"Clemente Fracassi","Writer":"Clemente Fracassi (screenplay), Antonio Ghislanzoni (based on the libretto by)","Actors":"Sophia Loren, Renata Tebaldi, Lois Maxwell, Ebe Stignani","Plot":"Aida, featuring the actress Sophia Lauren, was a film adaptation of a theatre performance written by Verdi. The plot revolves around the character Radames who falls in love with what he thinks is a slave in a country his armies has conuered. The young woman is actually the daughter of the leader he ousted.","Language":"Italian, English","Country":"Italy","Awards":"N/A","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMDA5YTM4YzctNjU4YS00ZjdmLTliNDAtMWNkNTI0ZWEwNTRlXkEyXkFcGdeXVyMjI4NzAzNjg@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"5.5","imdbVotes":"127","imdbID":"tt0045483","Type":"movie","Response":"True"},
{"Title":"It Pays to Advertise","Year":"1931","Rated":"N/A","Released":"19 Feb 1931","Runtime":"63 min","Genre":"Comedy","Director":"Frank Tuttle","Writer":"Ethel Doherty (adaptation), Walter C. Hackett (play), Arthur Kober (adaptation), Roi Cooper Megrue (play)","Actors":"Norman Foster, Carole Lombard, Richard 'Skeets' Gallagher, Eugene Pallette","Plot":"To prove his thesis that any product--even one that doesn't exist--can be merchandized if it is advertised properly, a young man gets together with his father's savvy secretary to market a ...","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BZWE0YmY0YjMtMDg2YS00ZWVmLWI1ODYtZGU1MzBkN2EyOWNkXkEyXkFcGdeXVyNTY4NjI2OTA@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"5.8","imdbVotes":"43","imdbID":"tt0022006","Type":"movie","Response":"True"},
{"Title":"The Blizzard","Year":"1923","Rated":"N/A","Released":"01 Jan 1923","Runtime":"101 min","Genre":"Drama","Director":"Mauritz Stiller","Writer":"Selma Lagerlöf (novel), Mauritz Stiller","Actors":"Gustav Aronson, Stina Berg, Hugo Björne, Pauline Brunius","Plot":"Gunnar Hede, a young Swedish man, wants to become a professional musician, but when his father suddenly dies he is pressured by his family to take over the family business, raising and ...","Language":"N/A","Country":"Sweden","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMjE1OTk3NjAyMF5BMl5BanBnXkFtZTgwNDIwNT2MzE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.0","imdbVotes":"108","imdbID":"tt0014108","Type":"movie","Response":"True"},
{"Title":"The Suad","Year":"2011","Rated":"N/A","Released":"07 Oct 2011","Runtime":"108 min","Genre":"Horror, Thriller","Director":"Jaime Osorio Maruez","Writer":"Tania Cardenas (script consultant), Jaime Osorio Maruez (story and screenplay), Diego Vivanco","Actors":"Juan Pablo Barragán, Alejandro Aguilar, Mauricio Navas, Juan David Restrepo","Plot":"After losing contact with a military base, a high mountain unit is sent to investigate. Upon arrival, they find only a woman in chains. Isolation and the impossibility of escape serve to undermine the soldiers' judgment.","Language":"Spanish","Country":"Colombia, Argentina, Spain","Awards":"1 win & 1 nomination.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTExNDI2NDcxNTNeTJeWpwZ15BbWU3MDg1Mjg2OTY@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"5.2","imdbVotes":"1,199","imdbID":"tt1547084","Type":"movie","Response":"True"},
{"Title":"The Hairy Bikers' Cookbook","Year":"2006–","Rated":"N/A","Released":"17 Jan 2006","Runtime":"29 min","Genre":"Documentary","Director":"N/A","Writer":"N/A","Actors":"Simon King, David Myers","Plot":"N/A","Language":"English","Country":"UK","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"7.4","imdbVotes":"56","imdbID":"tt0497293","Type":"series","totalSeasons":"3","Response":"True"},
{"Title":"Punisher: War Zone","Year":"2008","Rated":"R","Released":"05 Dec 2008","Runtime":"103 min","Genre":"Action, Crime, Drama","Director":"Lexi Alexander","Writer":"Nick Santora, Art Marcum, Matt Holloway","Actors":"Ray Stevenson, Dominic West, Doug Hutchison, Colin Salmon","Plot":"After hunting down and killing hundreds of violent criminals, Frank Castle, aka The Punisher, faces his most deadly foe yet: Jigsaw.","Language":"English","Country":"USA, Canada, Germany","Awards":"1 win & 1 nomination.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTM4OTyODk0NF5BMl5BanBnXkFtZTcwMzwNDwMg@@._V1_SX300.jpg","Metascore":"30","imdbRating":"6.0","imdbVotes":"49,199","imdbID":"tt0450314","Type":"movie","Response":"True"},
{"Title":"The Thing Below","Year":"2004","Rated":"R","Released":"07 Jan 2004","Runtime":"94 min","Genre":"Horror, Sci-Fi, Thriller","Director":"Jim Wynorski","Writer":"Raul Inglis, Keith Shaw","Actors":"Billy Warlock, Kurt Max Runte, Catherine Lough Hagguist, Peter Graham-Gaudreau","Plot":"A top secret drilling platform in the Gulf of Mexico raises a dormant alien creature from the depths. Once loose, the creature goes on a murderous rampage.","Language":"English","Country":"Canada","Awards":"N/A","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTg0OTczNTUyMl5BMl5BanBnXkFtZTcwMTk4MjAzM@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"2.3","imdbVotes":"742","imdbID":"tt0382443","Type":"movie","Response":"True"},
{"Title":"Kabut sutra ungu","Year":"1979","Rated":"N/A","Released":"N/A","Runtime":"127 min","Genre":"Drama","Director":"Sjuman Djaya","Writer":"Sjuman Djaya, Ike Soepomo","Actors":"Jenny Rachman, Roy Marten, Wahab Abdi, Zainal Abidin","Plot":"N/A","Language":"Indonesian","Country":"Indonesia","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"6.4","imdbVotes":"9","imdbID":"tt1797422","Type":"movie","Response":"True"},
{"Title":"They Looked Alike","Year":"1915","Rated":"N/A","Released":"05 Jan 1915","Runtime":"N/A","Genre":"Short, Comedy","Director":"Frank Griffin","Writer":"E.W. Sargent","Actors":"C.W. Ritchie, Raymond McKee, Harry Lorraine, Oliver Hardy","Plot":"Two tramps look so much alike that they can outfox the police time after time. When one of them is locked in a shack, the police manage to catch the other one and expose the trick.","Language":"English","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"5.7","imdbVotes":"10","imdbID":"tt0248544","Type":"movie","Response":"True"},
{"Title":"The Triangle Factory Fire Scandal","Year":"1979","Rated":"N/A","Released":"30 Jan 1979","Runtime":"120 min","Genre":"Drama","Director":"Mel Stuart","Writer":"Mel Brez, Ethel Brez","Actors":"David Dukes, Tovah Feldshuh, Lauren Frost, Janet Margolin","Plot":"The story of a fire in the Triangle Shirt Mfg. Co. building in New York City in 1911 that resulted in the deaths of 146 employees, mostly young women. The ensuing investigation revealed the company's almost total disregard for its workers' safety in pursuit of increased production and profits, and resulted, among other things, in the passage of new worker safety laws and the formation of the International Ladies Garment Workers Union.","Language":"English","Country":"USA","Awards":"Won 1 Primetime Emmy. Another 2 nominations.","Poster":"N/A","Metascore":"N/A","imdbRating":"7.3","imdbVotes":"95","imdbID":"tt0080048","Type":"movie","Response":"True"},
{"Title":"Bulandi","Year":"2000","Rated":"N/A","Released":"07 Jan 2000","Runtime":"175 min","Genre":"Drama, Musical, Romance","Director":"Rama Rao Tatineni","Writer":"Aadesh K. Arjun (dialogue), Erode Sounder (story)","Actors":"Anil Kapoor, Rekha, Raveena Tandon, Rajinikanth","Plot":"A noble family presides over a small town in India.","Language":"Hindi","Country":"India","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMTcwMzgyNTkwMV5BMl5BanBnXkFtZTgwNDgzOTk1MDE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"5.3","imdbVotes":"451","imdbID":"tt0230055","Type":"movie","Response":"True"},
{"Title":"Psychopath","Year":"2009","Rated":"N/A","Released":"14 Aug 2009","Runtime":"78 min","Genre":"Horror","Director":"Robert Elkins","Writer":"Robert Elkins","Actors":"Kyle Billeter, Glenn Leftwich, Lawrence Wiencek, DaNae West","Plot":"Sarah misses a desperate call from her stranded sister sets off with friends to find her in the backwoods town of Raven's Neck, home to a brutal escaped mental patient.","Language":"English","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"5.2","imdbVotes":"13","imdbID":"tt1522253","Type":"movie","Response":"True"},
{"Title":"Take a Chance","Year":"1918","Rated":"N/A","Released":"15 Dec 1918","Runtime":"10 min","Genre":"Comedy, Short","Director":"Alfred J. Goulding","Writer":"N/A","Actors":"Harold Lloyd, 'Snub' Pollard, Bebe Daniels, William Blaisdell","Plot":"N/A","Language":"English","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"6.5","imdbVotes":"179","imdbID":"tt0009678","Type":"movie","Response":"True"},
{"Title":"State 194","Year":"2012","Rated":"PG","Released":"17 May 2013","Runtime":"98 min","Genre":"Documentary","Director":"Dan Setton","Writer":"Elise Pearlstein, Dan Setton","Actors":"Salam Fayyad, Mahmoud Abbas, Tzipi Livni, Avi Dichter","Plot":"A look deep inside Israel and Palestine at the men and women trying to seize a historic opportunity to end the conflict and make implementing the two-state solution a reality.","Language":"English, Arabic, Hebrew","Country":"Israel, USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMzxNDc3NzcyNV5BMl5BanBnXkFtZTcwOTI0MDE1O@@._V1_SX300.jpg","Metascore":"63","imdbRating":"5.6","imdbVotes":"41","imdbID":"tt2324918","Type":"movie","Response":"True"},
{"Title":"Old English","Year":"1930","Rated":"PASSED","Released":"27 Sep 1930","Runtime":"85 min","Genre":"Drama","Director":"Alfred E. Green","Writer":"John Galsworthy (by), Walter Anthony (screen adaptation), Maude T. Howell (screen adaptation)","Actors":"George Arliss, Doris Lloyd, Harrington Reynolds, Reginald Sheffield","Plot":"An old man unethically provides an income for his two grandchildren.","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMjIwMWIzZmYtZjI5OC00YzM2LTljY2UtMmRmMzViMmFmY2E1XkEyXkFcGdeXVyNDY1NzU5NjY@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"6.2","imdbVotes":"24","imdbID":"tt0021203","Type":"movie","Response":"True"},
{"Title":"De grens","Year":"1984","Rated":"N/A","Released":"20 Sep 1984","Runtime":"100 min","Genre":"Thriller","Director":"Leon de Winter","Writer":"Leon de Winter","Actors":"Johan Leysen, Linda van Dyck, Angela Winkler, André Dussollier","Plot":"N/A","Language":"Dutch","Country":"Netherlands","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"6.1","imdbVotes":"22","imdbID":"tt0087364","Type":"movie","Response":"True"},
{"Title":"Shikhandi Kotha","Year":"2013","Rated":"N/A","Released":"19 Apr 2013","Runtime":"103 min","Genre":"Drama, Family","Director":"Mohammad Hannan","Writer":"Anan Zaman (script), Mohammad Hannan (screenplay)","Actors":"Rakhal Sobuj, Jayanto Chattopadhyay, Rokeya Prachy, Mirana Zaman","Plot":"After giving birth of tow girl Ramela have a boy child. Both Ramela and his husband Ramjed Molla are happy at this. Ramjed named him Ratan and cares him a lot as he is the only boy child. But at the adolescence period his physical changes exposed like a girl. His family and the villagers realizes himself as an eunuch. But, Ramela denies to send him to third gender's lodge. Later, he becomes obstacle to his sister's marriage and his father scolds and beats him up. He then realizes that society will not accept him and goes to the third gender's place. There he grows under the supervision of Kali Masi as Ratna.","Language":"Bengali","Country":"Bangladesh","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt5735632","Type":"movie","Response":"True"},
{"Title":"After the Apocalypse","Year":"2004","Rated":"N/A","Released":"12 Mar 2004","Runtime":"72 min","Genre":"Sci-Fi, Drama, Fantasy","Director":"Yasuaki Nakajima","Writer":"Yasuaki Nakajima","Actors":"Jacueline Bowman, Velina Georgi, Zorikh Leuidre, Oscar Lowe","Plot":"AFTER THE APOCALYPSE is a futuristic drama about five survivors trying to make sense of a New World after a devastating urban catastrophe challenges their basic human needs. Set in a bleak, post-urban landscape in the aftermath of the Third World War, the film presents a strangely limited environment where a single woman and four men are forced to communicate without words as a result of destructive gasses from the war. When their pasts are erased by the war, they are forced to recreate their lives both individually and collectively.","Language":"N/A","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMTg2MTA1NDkwNl5BMl5BanBnXkFtZTcwMDY3NzcyM@@._V1_SX300.jpg","Metascore":"53","imdbRating":"6.0","imdbVotes":"212","imdbID":"tt0404745","Type":"movie","Response":"True"},
{"Title":"Genius","Year":"2016","Rated":"PG-13","Released":"10 Jun 2016","Runtime":"104 min","Genre":"Biography, Drama","Director":"Michael Grandage","Writer":"A. Scott Berg (based on the book by), John Logan (screenplay)","Actors":"Colin Firth, Nicole Kidman, Laura Linney, Jude Law","Plot":"When, one day of 1929, writer Thomas Wolfe, decided to keep the appointment made by Max Perkins, editor at Scribner's, he had no illusions: his manuscript would be turned down as had invariably been the case. But, to his happy amazement, his novel, which was to become \"Look Homeward, Angel\", was accepted for publication. The only trouble was that it was overlong (300 pages) and had to be reduced. Although reluctant to see his poetic prose trimmed, Wolfe agreed and helped by Perkins, who had become a true friend, with the result that it instantly became a favorite with the critics and best seller. Success was even greater in 1935 when \"Of Time end the River\" appeared, but the fight for reducing Wolfe's logorrheic written expression had been even longer, with 5,000 pages, Perkins managed to cut 90,000 words from the book, and bitter ultimately taking its toll, the relationships between the two men gradually deteriorating. Wolfe did not feel grateful to Perkins any longer but had started resenting him for owing his success to him.","Language":"English","Country":"UK, USA","Awards":"3 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjMwNzM3NzY0M15BMl5BanBnXkFtZTgwODMwMj1ODE@._V1_SX300.jpg","Metascore":"56","imdbRating":"6.6","imdbVotes":"3,141","imdbID":"tt1703957","Type":"movie","Response":"True"},
{"Title":"Pharaoh","Year":"1966","Rated":"N/A","Released":"11 Mar 1966","Runtime":"180 min","Genre":"Drama","Director":"Jerzy Kawalerowicz","Writer":"Boleslaw Prus (novel), Tadeusz Konwicki (screenplay), Jerzy Kawalerowicz (screenplay)","Actors":"Jerzy Zelnik, Wieslawa Mazurkiewicz, Barbara Brylska, Krystyna Mikolajewska","Plot":"Young Pharaoh Ramses XIII clashes with Egypt's clergy over influence on the affairs of the state and its coffers.","Language":"Polish","Country":"Poland","Awards":"Nominated for 1 Oscar. Another 1 nomination.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjExNDExNDYzOF5BMl5BanBnXkFtZTcwNzAwNDMyM@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.6","imdbVotes":"1,163","imdbID":"tt0060401","Type":"movie","Response":"True"},
{"Title":"Mindhunters","Year":"2004","Rated":"R","Released":"13 May 2005","Runtime":"106 min","Genre":"Crime, Horror, Mystery","Director":"Renny Harlin","Writer":"Wayne Kramer (story), Wayne Kramer (screenplay), Kevin Brodbin (screenplay)","Actors":"Eion Bailey, Clifton Collins Jr., Will Kemp, Val Kilmer","Plot":"On a remote island, the FBI has a training program for their psychological profiling division, called \"Mindhunters\", used to track down serial killers. The training goes horribly wrong, however, when a group of seven young agents discover that one of them is a serial killer, and is setting about slaying the others. Can the few that are left figure out who the killer is in time?","Language":"English","Country":"USA, UK, Netherlands, Finland","Awards":"4 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTAwOTY3NDM1NjNeTJeWpwZ15BbWU3MDEzMjU1MjE@._V1_SX300.jpg","Metascore":"33","imdbRating":"6.4","imdbVotes":"49,632","imdbID":"tt0297284","Type":"movie","Response":"True"},
{"Title":"Ararat","Year":"2002","Rated":"R","Released":"06 Dec 2002","Runtime":"115 min","Genre":"Drama, War","Director":"Atom Egoyan","Writer":"Atom Egoyan","Actors":"Simon Abkarian, Charles Aznavour, Christopher Plummer, Arsinée Khanjian","Plot":"Interrogated by a customs officer, a young man recounts how his life was changed during the making of a film about the Armenian genocide.","Language":"English, Armenian, French, German, Turkish","Country":"Canada, France","Awards":"12 wins & 13 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BOTIxNTg4NTg5OV5BMl5BanBnXkFtZTcwOTk2MjAwM@@._V1_SX300.jpg","Metascore":"62","imdbRating":"6.6","imdbVotes":"8,933","imdbID":"tt0273435","Type":"movie","Response":"True"},
{"Title":"Rrugicat ë kërkonin diell","Year":"1975","Rated":"N/A","Released":"22 Feb 1975","Runtime":"2 h 40 min","Genre":"Drama, Action","Director":"Saimir Kumbaro, Rikard Ljarja","Writer":"Dhimitër Xhuvani","Actors":"Mevlan Shanaj, Rikard Ljarja, Demir Hyskja, Sheri Mita","Plot":"N/A","Language":"N/A","Country":"N/A","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt0295576","Type":"movie","Response":"True"},
{"Title":"Gasolin'","Year":"2006","Rated":"N/A","Released":"10 Mar 2006","Runtime":"92 min","Genre":"Documentary, Biography, Music","Director":"Anders Østergaard","Writer":"Anders Østergaard","Actors":"Kim Larsen, Franz Beckerlee, Wili Jönsson, Søren Berlev","Plot":"This documentary tells us the story of the Danish rock band, Gasolin'.","Language":"Danish","Country":"Denmark","Awards":"2 wins & 1 nomination.","Poster":"N/A","Metascore":"N/A","imdbRating":"7.2","imdbVotes":"294","imdbID":"tt0799770","Type":"movie","Response":"True"},
{"Title":"The Governor","Year":"1995–1996","Rated":"N/A","Released":"14 May 1995","Runtime":"60 min","Genre":"Crime, Drama","Director":"N/A","Writer":"N/A","Actors":"Janet McTeer, Derek Martin, Ron Donachie, David Nicholls","Plot":"Helen Hewitt is first woman put in charge of Barfield, a maximum security prison that had been nearly destroyed by a disastrous riot. Despite being greeted with open hostility by inmates and little enthusiasm by prison staff, she is determined to clean up the place.","Language":"English","Country":"UK","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"7.6","imdbVotes":"60","imdbID":"tt0111988","Type":"series","totalSeasons":"N/A","Response":"True"},
{"Title":"The Ruling Passion","Year":"1912","Rated":"N/A","Released":"13 Mar 1912","Runtime":"N/A","Genre":"Drama, Short","Director":"N/A","Writer":"N/A","Actors":"Henry B. Walthall","Plot":"N/A","Language":"English","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt0359922","Type":"movie","Response":"True"},
{"Title":"Coral Reef Adventure","Year":"2003","Rated":"N/A","Released":"14 Feb 2003","Runtime":"45 min","Genre":"Documentary","Director":"Greg MacGillivray","Writer":"Jack Stephens (narration), Osha Gray Davidson, Stephen Judson","Actors":"Liam Neeson, Howard Hall, Michele Hall, Jean-Michel Cousteau","Plot":"Take a once in a lifetime journey across the South Pacific for a spectacular IMAX adventure. Joy, ecstasy, a spiritual high: these words describe the exhilaration of diving a pristine coral...","Language":"English","Country":"USA, Singapore, Taiwan","Awards":"2 wins & 1 nomination.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjE2MzcwMDczNF5BMl5BanBnXkFtZTcwMDc3NDyM@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.0","imdbVotes":"450","imdbID":"tt0270291","Type":"movie","Response":"True"},
{"Title":"Penrod and Sam","Year":"1931","Rated":"UNRATED","Released":"03 Oct 1931","Runtime":"71 min","Genre":"Drama, Comedy","Director":"William Beaudine","Writer":"Booth Tarkington (story), Waldemar Young (screen play)","Actors":"Leon Janney, Frank Coghlan Jr., Cameo the Dog, Margaret Maruis","Plot":"Two mischievous schoolboys, Penrod and Sam, are constantly in trouble at school. They start their own club, the In-Or-In club, of which they are the only members. Two of their schoolmates, Georgie and Rodney, want to get into the club but are not allowed because they're always ratting out Penrod and Sam to the adults, and getting them in trouble. However, George's father complains to Penrod's father about it, who tells Penrod that they must admit the two boys. Penrod and Sam decide that if they're being forced to accept the two stool pigeons, they'll make them pay for it.","Language":"English","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"6.4","imdbVotes":"108","imdbID":"tt0022261","Type":"movie","Response":"True"},
{"Title":"Eden","Year":"2012","Rated":"R","Released":"19 Jul 2013","Runtime":"98 min","Genre":"Crime, Drama","Director":"Megan Griffiths","Writer":"Richard B. Phillips (screenplay), Megan Griffiths (screenplay), Richard B. Phillips (story), Chong Kim (story)","Actors":"Jamie Chung, Beau Bridges, Matt O'Leary, Eddie Martinez","Plot":"A young Korean-American girl, abducted and forced into prostitution by domestic human traffickers, joins forces with her captors in a desperate plea to survive.","Language":"English, Chinese, Spanish","Country":"USA","Awards":"9 wins & 4 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNzAxNTg3NTUzN15BMl5BanBnXkFtZTcwMTMwMDcwO@@._V1_SX300.jpg","Metascore":"63","imdbRating":"6.7","imdbVotes":"6,569","imdbID":"tt1734433","Type":"movie","Response":"True"},
{"Title":"Cold Blade","Year":"2011","Rated":"N/A","Released":"17 Jun 2011","Runtime":"N/A","Genre":"Short, Thriller","Director":"Sam Dickenson","Writer":"N/A","Actors":"N/A","Plot":"Detective Trev and Johnson both find a killer on the loose who has been killing off innocent victims in the town of Guildford, Surrey. They work together to find clues to find the killer. Detective Trev who is all alone because his wife has died puts maximum effort trying to solve this case.","Language":"English","Country":"UK","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt1972626","Type":"movie","Response":"True"},
{"Title":"The Parking Lot Movie","Year":"2010","Rated":"N/A","Released":"06 Aug 2010","Runtime":"74 min","Genre":"Documentary","Director":"Meghan Eckman","Writer":"N/A","Actors":"Patrick Baran, John Beers, Chris Farina, Tyler Magill","Plot":"The Parking Lot Movie is a documentary about a singular parking lot in Charlottesville, Virginia. The film follows a select group of parking lot attendants and their strange rite of passage...","Language":"English","Country":"USA","Awards":"1 nomination.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTI5NDE4ODY5NF5BMl5BanBnXkFtZTcwMTg4Mzk5Mw@@._V1_SX300.jpg","Metascore":"63","imdbRating":"7.0","imdbVotes":"1,584","imdbID":"tt1504300","Type":"movie","Response":"True"},
{"Title":"Sweet Music","Year":"1935","Rated":"PASSED","Released":"23 Feb 1935","Runtime":"100 min","Genre":"Musical, Romance","Director":"Alfred E. Green","Writer":"Jerry Wald (story), Jerry Wald (screenplay), Carl Erickson (screenplay), Warren Duff (screenplay)","Actors":"Rudy Vallee, Ann Dvorak, Ned Sparks, Helen Morgan","Plot":"College band-leader \"Skip\" Houston keeps his band together after graduation, they turn professional, and they are a big hit on the radio and in nightclubs. He falls in love with Bonnie ...","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMj0NGRlYzItNj1MS00ZWYzLWExNWItY2E4ZWUyNWFhND1XkEyXkFcGdeXVyMjc3MjgzOTU@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"6.4","imdbVotes":"85","imdbID":"tt0027064","Type":"movie","Response":"True"},
{"Title":"The Ranchero's Revenge","Year":"1913","Rated":"N/A","Released":"02 Jun 1913","Runtime":"17 min","Genre":"Western, Short","Director":"D.W. Griffith","Writer":"N/A","Actors":"Lionel Barrymore, Harry Carey, Claire McDowell, Clarence Barr","Plot":"The heartless woman with her partner answered the ranchero's call for a wife. Then the adventuress soon discovered she was not as heartless as she at first imagined. She learned to love and...","Language":"English","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt0003313","Type":"movie","Response":"True"},
{"Title":"Out of the Dark","Year":"2014","Rated":"R","Released":"10 Apr 2015","Runtime":"92 min","Genre":"Horror, Thriller","Director":"Lluís uílez","Writer":"Javier Gullón (screenplay), David Pastor (screenplay), Àlex Pastor (screenplay)","Actors":"Julia Stiles, Scott Speedman, Stephen Rea, Pixie Davies","Plot":"A young family moves to South America as the wife takes over her father's manufacturing plant in the area. They soon find themselves haunted by the ghosts of young children, leading them to a dark history and sinister behavior on the part of an American company.","Language":"English","Country":"USA, Colombia, Spain","Awards":"N/A","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMzY5MDE1ODE2N15BMl5BanBnXkFtZTgwMDY5NTc5MzE@._V1_SX300.jpg","Metascore":"33","imdbRating":"4.7","imdbVotes":"2,723","imdbID":"tt2872724","Type":"movie","Response":"True"},
{"Title":"The Surface","Year":"2014","Rated":"N/A","Released":"15 May 2015","Runtime":"90 min","Genre":"Drama, Thriller","Director":"Gil Cates Jr.","Writer":"Jeff Gendelman","Actors":"Sean Astin, Mimi Rogers, Chris Mulkey, John Emmet Tracy","Plot":"Two strangers, both at the end of their rope, suddenly meet in the middle of the unpredictable waters of Lake Michigan.","Language":"English","Country":"USA","Awards":"1 nomination.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNTEyNjk5MzUxNl5BMl5BanBnXkFtZTgwODU4MjUzNTE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"4.7","imdbVotes":"552","imdbID":"tt3074578","Type":"movie","Response":"True"},
{"Title":"La vendetta","Year":"2007–","Rated":"N/A","Released":"29 Oct 2007","Runtime":"N/A","Genre":"Action, Crime, Drama","Director":"N/A","Writer":"Jun Lana, R.J. Nuevas","Actors":"Sunshine Dizon, Dante Rivero, Caridad Sanchez","Plot":"The story revolves around the three Cardinale sisters who clash in their fight for love and their rights to the family's fortune. When one of them dies, the two remaining siblings, as well as everyone linked to them, become primary suspects. The motive for the murder, as well as the person behind it, is the mystery that has to be solved.","Language":"Tagalog, Filipino, English","Country":"Philippines","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"8.3","imdbVotes":"13","imdbID":"tt1119177","Type":"series","totalSeasons":"1","Response":"True"},
{"Title":"O Jerusalem","Year":"2006","Rated":"R","Released":"18 Oct 2006","Runtime":"100 min","Genre":"Drama","Director":"Élie Chouraui","Writer":"Élie Chouraui, Didier Le Pêcheur","Actors":"JJ Feild, Saïd Taghmaoui, Maria Papas, Patrick Bruel","Plot":"A tale of friendship between two men, one Jewish and the other Arab, as the state of Israel is being created.","Language":"English, Arabic, Hebrew","Country":"France, UK, Italy, Greece, Israel, USA","Awards":"N/A","Poster":"N/A","Metascore":"39","imdbRating":"6.2","imdbVotes":"754","imdbID":"tt0443448","Type":"movie","Response":"True"},
{"Title":"The Soldier","Year":"1982","Rated":"R","Released":"27 Aug 1982","Runtime":"96 min","Genre":"Action, Adventure, Thriller","Director":"James Glickenhaus","Writer":"James Glickenhaus","Actors":"Ken Wahl, Alberta Watson, Jeremiah Sullivan, William Prince","Plot":"The Russians steal a nuclear device and are stating that unless the Israelis pull out from the West bank, they will detonate it, which they have planted in an oil field and if it should go off; 50% of the World's oil will be contaminated. And the Israelis are unwilling to cooperate and the Americans knowing that they can't allow this are making preparations to force the Israelis off the West bank. The President then calls the Director of the CIA to do something about this. The Director assigns the agent who works outside the official channels codenamed the Soldier. He starts by trying to see if the Russians are indeed behind it but the Russians have him marked for termination. When he tries to contact the Director, the Russians placed a bomb in his office that leaves the soldier with no one but his team and the Israelis to help him.","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMTkyNTYwMTYwM15BMl5BanBnXkFtZTcwODYyMTM4NA@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"5.2","imdbVotes":"750","imdbID":"tt0084704","Type":"movie","Response":"True"},
{"Title":"Our Mrs. McChesney","Year":"1918","Rated":"N/A","Released":"18 Aug 1918","Runtime":"50 min","Genre":"Comedy, Drama","Director":"Ralph Ince","Writer":"Edna Ferber (play), George V. Hobart (play), Luther Reed","Actors":"Ethel Barrymore, Huntley Gordon, Wilfred Lytell, Lucille Lee Stewart","Plot":"N/A","Language":"N/A","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt0009465","Type":"movie","Response":"True"},
{"Title":"Wishcraft","Year":"2002","Rated":"R","Released":"25 Sep 2002","Runtime":"102 min","Genre":"Horror","Director":"Danny Graves, Richard Wenk","Writer":"Larry Katz","Actors":"Michael Weston, Alexandra Holden, Huntley Ritter, Austin Pendleton","Plot":"A high school student named Brett Bumpers receives a mysterious package one day. He does not know who gave it to him, but after a while he finds out that the totem within the package can give him 3 wishes. When the most beautiful girl in school, Samantha, invites him to dance on the next day, he knows for sure that his first wish has come true. He uses the second one to make Samantha fall in love with him, but when someone starts killing students in the school, he realizes that it has something to do with the totem. Now it's his responsibility to save their lives.","Language":"English","Country":"USA","Awards":"N/A","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNjcxMTwNDMyNl5BMl5BanBnXkFtZTcwMjA4MDkxM@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"5.2","imdbVotes":"1,545","imdbID":"tt0255702","Type":"movie","Response":"True"},
{"Title":"Direct Ish","Year":"2016","Rated":"N/A","Released":"19 Feb 2016","Runtime":"130 min","Genre":"Action, Comedy, Romance","Director":"Rajiv S. Ruia","Writer":"Bobby Khan, A.M. Turaz","Actors":"Arjun Bijlani, Rajneesh Duggal, Rajkumar Kanojia, Hemant Pandey","Plot":"Direct Ish is a love triangle where Dolly Pandey is the common love interest of Kabeer Bajpai an event organiser and Vicky Shukla President of Kashi Vidyapeeth.","Language":"Hindi","Country":"India","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"4.7","imdbVotes":"30","imdbID":"tt4340180","Type":"movie","Response":"True"},
{"Title":"The Cry Baby Killer","Year":"1958","Rated":"N/A","Released":"17 Aug 1958","Runtime":"70 min","Genre":"Crime, Drama, Thriller","Director":"Jus Addiss","Writer":"Leo Gordon (screenplay), Leo Gordon (story), Melvin Levy","Actors":"Harry Lauter, Jack Nicholson, Carolyn Mitchell, Brett Halsey","Plot":"17-year-old Jimmy Wallace is brutally beaten by Manny Cole and two of his teen-age punk friends, Joey and Al, because Manny wants to move in on Jimmy's girl, Carole Fields. Later, Jimmy shows up at the hangout of the teenage crowd to take Carole away, and challenges Manny to a fight. Manny's two buddies move in with brass knuckles, and one of them pulls a pistol, which falls to the ground in the scuffle. Jimmy picks it up and shoots Manny and Al. A police officer orders Jimmy to surrender, but he panics, thinking he killed the pair, and dives into a small storeroom, and holds a man, woman and her baby as hostages...","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMjAxNTAyMzUwN15BMl5BanBnXkFtZTcwMzM3MjA0M@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"5.1","imdbVotes":"315","imdbID":"tt0051500","Type":"movie","Response":"True"},
{"Title":"Smothered","Year":"2016","Rated":"N/A","Released":"29 Mar 2016","Runtime":"96 min","Genre":"Comedy, Horror","Director":"John Schneider","Writer":"John Schneider (story), John Schneider","Actors":"Kane Hodder, R.A. Mihailoff, Bill Moseley, Dane Rhodes","Plot":"Five horror icons ditch an unprofitable autograph signing convention to earn some extra cash haunting an RV park, but find themselves being haunted instead.","Language":"English","Country":"USA","Awards":"N/A","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTU2MDA1OTg4Nl5BMl5BanBnXkFtZTgwNTY4Nzk1ODE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"4.0","imdbVotes":"171","imdbID":"tt3040224","Type":"movie","Response":"True"},
{"Title":"Bansi Birju","Year":"1972","Rated":"N/A","Released":"N/A","Runtime":"N/A","Genre":"N/A","Director":"Prakash Verma","Writer":"Aziz uaisi (dialogue), Aziz uaisi (screenplay), Aziz uaisi (story), Prakash Verma (idea)","Actors":"Amitabh Bachchan, Jaya Bhaduri, Anwar Ali, Ramesh Bhatia","Plot":"Bansi and Birju get married in their village. But the villager's find out that Bansi is a prostitute.","Language":"Hindi","Country":"India","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"6.0","imdbVotes":"25","imdbID":"tt0068255","Type":"movie","Response":"True"},
{"Title":"Spoons","Year":"2005–","Rated":"N/A","Released":"30 Sep 2005","Runtime":"24 min","Genre":"Comedy","Director":"N/A","Writer":"N/A","Actors":"Elizabeth Bower, Kerry Godliman","Plot":"N/A","Language":"English","Country":"UK","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"7.5","imdbVotes":"113","imdbID":"tt0482428","Type":"series","totalSeasons":"N/A","Response":"True"},
{"Title":"The Amorous Ones","Year":"1968","Rated":"N/A","Released":"N/A","Runtime":"100 min","Genre":"Drama, Romance","Director":"Walter Hugo Khouri","Writer":"Walter Hugo Khouri","Actors":"Paulo José, Jacueline Myrna, Lilian Lemmertz, Anecy Rocha","Plot":"A young man in his early 30's ponders the state of his life while dealing with three women - his sister, his new girlfriend and his lover.","Language":"Portuguese","Country":"Brazil","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"6.8","imdbVotes":"49","imdbID":"tt0189351","Type":"movie","Response":"True"},
{"Title":"Arasangam","Year":"2008","Rated":"N/A","Released":"09 May 2008","Runtime":"N/A","Genre":"Action","Director":"R. Madhesh","Writer":"R. Madhesh (story)","Actors":"Vijayakanth, Biju Menon, Navneet Kaur, Sheryl Pinto","Plot":"N/A","Language":"Tamil","Country":"India, Canada","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"5.8","imdbVotes":"27","imdbID":"tt1320228","Type":"movie","Response":"True"},
{"Title":"Man Hunt","Year":"1941","Rated":"NOT RATED","Released":"20 Jun 1941","Runtime":"105 min","Genre":"Drama, Thriller, War","Director":"Fritz Lang","Writer":"Geoffrey Household (novel), Dudley Nichols (screenplay)","Actors":"Walter Pidgeon, Joan Bennett, George Sanders, John Carradine","Plot":"British hunter Thorndike vacationing in Bavaria has Hitler in his gun sight. He is captured, beaten, left for dead, and escapes back to London where he is hounded by German agents and aided by a young woman.","Language":"English, German","Country":"USA","Awards":"N/A","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNjUwMTzMTg0NV5BMl5BanBnXkFtZTgwMDM0Njc0MjE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.4","imdbVotes":"3,759","imdbID":"tt0033873","Type":"movie","Response":"True"},
{"Title":"The Ballad of Cable Hogue","Year":"1970","Rated":"R","Released":"22 May 1970","Runtime":"121 min","Genre":"Comedy, Drama, Romance","Director":"Sam Peckinpah","Writer":"John Crawford, Edmund Penney","Actors":"Jason Robards, Stella Stevens, David Warner, Strother Martin","Plot":"A hobo accidentally stumbles onto a water spring, and creates a profitable way station in the middle of the desert.","Language":"English","Country":"USA","Awards":"1 win & 1 nomination.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTwMjkwNjE0Ml5BMl5BanBnXkFtZTgwOTU5ODIyMTE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.3","imdbVotes":"6,417","imdbID":"tt0065446","Type":"movie","Response":"True"},
{"Title":"Tactical Force","Year":"2011","Rated":"R","Released":"09 Aug 2011","Runtime":"91 min","Genre":"Action, Comedy, Crime","Director":"Adamo P. Cultraro","Writer":"Adamo P. Cultraro","Actors":"Steve Austin, Michael Shanks, Michael Jai White, Adrian Holmes","Plot":"A training exercise for the LAPD SWAT Team goes terribly wrong when they find themselves pitted against two rival gangs while trapped in an abandoned Hangar, armed with nothing but blanks.","Language":"English","Country":"Canada","Awards":"N/A","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTM5NjAzOTI0M15BMl5BanBnXkFtZTcwMjAyNzAwNw@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"4.8","imdbVotes":"4,868","imdbID":"tt1458915","Type":"movie","Response":"True"},
{"Title":"Scandal","Year":"2012–","Rated":"TV-14","Released":"05 Apr 2012","Runtime":"43 min","Genre":"Drama, Thriller","Director":"N/A","Writer":"Shonda Rhimes","Actors":"Kerry Washington, Darby Stanchfield, Katie Lowes, Guillermo Díaz","Plot":"A former White House Communications Director starts her own crisis management firm only to realize her clients are not the only ones with secrets.","Language":"English","Country":"USA","Awards":"Nominated for 1 Golden Globe. Another 26 wins & 45 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTc2MDI1NTEwOV5BMl5BanBnXkFtZTgwMDEzODE4NzE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.9","imdbVotes":"52,078","imdbID":"tt1837576","Type":"series","totalSeasons":"6","Response":"True"},
{"Title":"Crying Wolf","Year":"2015","Rated":"N/A","Released":"10 Sep 2015","Runtime":"21 min","Genre":"Short, Thriller","Director":"Jason Rivers","Writer":"N/A","Actors":"Richard Buck, Jenn Day, Megan Gibson, Amethyst Gostlow-Crosslet","Plot":"A tenacious teenager searches for her missing friend after suspicions are raised about her whereabouts. As she becomes a would-be detective and works to uncover the truth, attempting to ...","Language":"English","Country":"UK","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMTUyNzUyOTE4MF5BMl5BanBnXkFtZTgwNDIyMz3NjE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.9","imdbVotes":"12","imdbID":"tt4990462","Type":"movie","Response":"True"},
{"Title":"The Devil's Gondola","Year":"1946","Rated":"N/A","Released":"21 Nov 1946","Runtime":"125 min","Genre":"Adventure","Director":"Carlo Campogalliani","Writer":"Max Calandri (subject), Carlo Campogalliani, Marcello Pagliero","Actors":"Loredana, Carlo Lombardi, Erminio Spalla, Nino Pavese","Plot":"N/A","Language":"Italian","Country":"Italy","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"4.8","imdbVotes":"9","imdbID":"tt0038570","Type":"movie","Response":"True"},
{"Title":"Proceso a la conciencia","Year":"1964","Rated":"N/A","Released":"N/A","Runtime":"1 h 22 min","Genre":"N/A","Director":"Agustín Navarro","Writer":"Agustín Navarro, Agustín Navarro","Actors":"Guillermo Battaglia, Carmen de la Maza, Mercedes Llambí, Conchita Núñez","Plot":"N/A","Language":"N/A","Country":"N/A","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt0058494","Type":"movie","Response":"True"},
{"Title":"Catherine the Great","Year":"1996","Rated":"N/A","Released":"28 Apr 1996","Runtime":"100 min","Genre":"Biography, Drama, History","Director":"Marvin J. Chomsky, John Goldsmith","Writer":"John Goldsmith, Frank Tudisco","Actors":"Catherine Zeta-Jones, Paul McGann, Ian Richardson, Brian Blessed","Plot":"In this romanticized biography, a small German principality's inexperienced princess, Catherine, becomes the bride of czarevitch Peter, the mad and abusive nephew and heir of the Russian czarina Elizabeth. From Elizabeth she learns the cynical ropes of wielding absolute imperial power at any cost, including sacrificing her lover, young guards officer Saltykov, who must give her an heir that Peter can't and is then sent abroad. After Elizabeth's death, she uickly moves to seize power with military and court support. She then works to enlarge and modernize the empire, again putting statesmanship ahead of her lover, a military genius who defeats the Ottomans and governs the conuered territories for her.","Language":"English","Country":"Germany, USA, Austria","Awards":"1 win.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjA2Nzg4MTg4MF5BMl5BanBnXkFtZTcwNDc1NjkxM@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"6.2","imdbVotes":"954","imdbID":"tt0112031","Type":"movie","Response":"True"},
{"Title":"The Magnificent Two","Year":"1967","Rated":"N/A","Released":"14 Jul 1967","Runtime":"100 min","Genre":"Comedy","Director":"Cliff Owen","Writer":"Sidney Green (screenplay), Richard Hills (screenplay), Michael Pertwee (screenplay), Peter Blackmore (screenplay), Michael Pertwee (story)","Actors":"Eric Morecambe, Ernie Wise, Margit Saad, Virgilio Teixeira","Plot":"Two salesmen travel to a small South American Country to peddle their wares. However the country is in the middle of a major conflict between the Government led by Diaz and the rebels led by Torez. When Torez is accidentally killed the rebels mistaken pick up one of the salesmen, Eric, as he looks like Torez. Eric and Ernie are promised millions to carry on the charade once the rebels take charge. However once Eric takes charge he finds himself back in danger as scheming general Carillo plans to remove the impostor from his role.","Language":"English","Country":"UK","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"5.2","imdbVotes":"227","imdbID":"tt0061938","Type":"movie","Response":"True"},
{"Title":"Heroes of the Night","Year":"1927","Rated":"N/A","Released":"03 Jan 1927","Runtime":"70 min","Genre":"Drama","Director":"Frank O'Connor","Writer":"F. Oakley Crawford (adaptation), F. Oakley Crawford (screenplay), James J. Tynan (story)","Actors":"Cullen Landis, Marian Nixon, Rex Lease, Wheeler Oakman","Plot":"N/A","Language":"English","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt0017987","Type":"movie","Response":"True"},
{"Title":"Smart Boys","Year":"2016","Rated":"N/A","Released":"N/A","Runtime":"N/A","Genre":"Romance","Director":"Anoopraj Mr.","Writer":"Anoopraj Mr.","Actors":"Noby Marcose, Venu Nariyapuram, Saju Navodaya, Kochu Preman","Plot":"N/A","Language":"Malayalam","Country":"India","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BNTAxMTUxMjYtYm3My00ZWJlLWE1YWItMDA2ZDE4ZDhlN2IxXkEyXkFcGdeXVyNj2NzIzODM@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt5299266","Type":"movie","Response":"True"},
{"Title":"The Marshal of Windy Hollow","Year":"1972","Rated":"N/A","Released":"N/A","Runtime":"85 min","Genre":"Western","Director":"Jerry Whittington","Writer":"Norman Sheldon","Actors":"Sunset Carson, Ken Maynard, Tex Ritter, Tex Barr","Plot":"The Marshal (Sunset Carson) calls in the head of the Texas Rangers (Ken Maynard) to track down the disappearance of a entire Wagon Train. Ken Maynard (Texas Ranger) finds out that the outlaws were robbing the Settlers, stealing the Gold from the Wagons and dumping the Wagons with the Settlers into the Canyon River. The Texas Rangers trapped the Outlaws in the Canyon, some were blown up in there Canyon hide-out and others were arrested by Marshal Sunset Carson and brought into the town of Windy Hollow for trial.","Language":"English","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"8.7","imdbVotes":"9","imdbID":"tt0314360","Type":"movie","Response":"True"},
{"Title":"2 Hip 4 TV","Year":"1988–","Rated":"N/A","Released":"10 Sep 1988","Runtime":"60 min","Genre":"Comedy","Director":"N/A","Writer":"N/A","Actors":"Stacy Dunn","Plot":"N/A","Language":"English","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"8.5","imdbVotes":"6","imdbID":"tt0124931","Type":"series","totalSeasons":"1","Response":"True"},
{"Title":"Cheluvina Chittara","Year":"2007","Rated":"N/A","Released":"22 Jun 2007","Runtime":"150 min","Genre":"Crime, Drama, Romance","Director":"S. Narayan","Writer":"S. Narayan","Actors":"Ganesh, Amoolya, Asharani, Suresh Chandra","Plot":"Maadesha is a small-time two-wheeler mechanic. A young schoolgirl from a rich local don family falls in love with him. Since they know her family will kill Maadesha if they go to ask their permission, they elope and get married in a sub-registrar's office. They are lured by her Uncle who promises good things for them. Aishwarya's father catches hold of them and his gangsters beat Maadesha black and blue and threatens to kill him. Aishwarya who had been refusing to remove the sacred Mangalasutra (ThaaLi) finally relents in order to save his life. Tragically, Maadesha ends up going mad. After two years, Aishwarya has a baby after marrying another man and is heartbroken to see that the love of her life will never have a meaningful life because of her.","Language":"Kannada","Country":"India","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"6.3","imdbVotes":"16","imdbID":"tt3171702","Type":"movie","Response":"True"},
{"Title":"Arabesue","Year":"1966","Rated":"UNRATED","Released":"05 May 1966","Runtime":"105 min","Genre":"Action, Adventure, Crime","Director":"Stanley Donen","Writer":"Julian Mitchell (screenplay), Stanley Price (screenplay), Peter Stone (screenplay), Gordon Cotler (novel)","Actors":"Gregory Peck, Sophia Loren, Alan Badel, Kieron Moore","Plot":"Professor David Pollock is an expert in ancient Arabic hieroglyphics. A Middle Eastern Prime Minister convinces Pollock to infiltrate the organization of a man named Beshraavi, who is involved in a plot against the Prime Minister. The nature of the plot is believed to be found in a hieroglyphic code. Beshraavi's mistress, Yasmin Azir is a mystery intertwined in the plot. Pollock needs her help, but when she repeatedly seems to double cross him in one escapade after another, he can't decide on whose side she is working. Ultimately working together, Pollock and Yasmin decipher the plot and set out to stop an assassination of the Prime Minister.","Language":"English","Country":"USA","Awards":"Won 1 BAFTA Film Award. Another 1 win & 4 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTk4MDc2NTA1NV5BMl5BanBnXkFtZTcwOTEyOTI0M@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"6.6","imdbVotes":"4,572","imdbID":"tt0060121","Type":"movie","Response":"True"},
{"Title":"Criminally Insane 2","Year":"1987","Rated":"N/A","Released":"N/A","Runtime":"70 min","Genre":"Horror","Director":"Nick Millard","Writer":"Nick Millard (screenplay)","Actors":"Priscilla Alden, Michael Flood, Jane Lambert, Robert Copple","Plot":"A mental hospital, faced with a severe decrease in funding, is forced to release mass-murderer Ethel Janowski into a halfway house. Ethel is psychotic, delusional and has a hefty appetite. In fact, her killing spree began 13 years before with the murder of her grandmother, who had forced her to go on a diet. Now that she's tasted the home-cooked fare at the halfway house, she'll do absolutely anything to get more.","Language":"English","Country":"USA","Awards":"N/A","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTI3NzcyMj2NF5BMl5BanBnXkFtZTcwNDEyMDYzM@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"1.8","imdbVotes":"333","imdbID":"tt0088959","Type":"movie","Response":"True"},
{"Title":"Thoda Lutf Thoda Ish","Year":"2015","Rated":"N/A","Released":"10 Jul 2015","Runtime":"N/A","Genre":"Comedy, Romance","Director":"Sachin Gupta","Writer":"Sachin Gupta","Actors":"Bhavita Anand, Rakesh Bedi, Sanjay Mishra, Sushmita Mukherjee","Plot":"Two good for nothing boys Jhumroo and Ghungroo are best examples of fools who keep roaming around the whole day. Their sole motive in life is to have fun, befriend girls, go to parties, get drunk and chill. They find impish ways to get in touch with girls. They are also desperate to get a job, but in their comical attempt they receive yet more embarrassment. After couple of disasters they get a job at a newly opened beauty parlor run by two smart girls. Their dream has come true. They are around girls all the time. But this is just the beginning of their hilarious trauma and a journey full of unexpected twists. - A roller-coaster ride for them and guffaws for viewers.","Language":"Hindi","Country":"India","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BZGExOG4OWYtN2M4OC00NzAxLTlkZjMtMmUwMjMyYT3OGJmXkEyXkFcGdeXVyNDMzMTgwNzM@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"4.1","imdbVotes":"38","imdbID":"tt4859310","Type":"movie","Response":"True"},
{"Title":"Les Bougon","Year":"2008–","Rated":"N/A","Released":"13 Oct 2008","Runtime":"N/A","Genre":"Comedy","Director":"N/A","Writer":"N/A","Actors":"Patrick Bonnel, Cathy Bodet, Olivier Broche, Vincent Debost","Plot":"N/A","Language":"French","Country":"France","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"7.4","imdbVotes":"11","imdbID":"tt1281482","Type":"series","totalSeasons":"1","Response":"True"},
{"Title":"Lake of Tears","Year":"1966","Rated":"N/A","Released":"13 Nov 1966","Runtime":"130 min","Genre":"N/A","Director":"Tomotaka Tasaka","Writer":"Naoyuki Suzuki","Actors":"Yoshiko Sakuma, Katsuo Nakamura, Ganjirô Nakamura, Hisano Yamaoka","Plot":"N/A","Language":"Japanese","Country":"Japan","Awards":"3 wins.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTExNzI4MDYxMTVeTJeWpwZ15BbWU4MDU1OTI3MjEx._V1_SX300.jpg","Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt0324357","Type":"movie","Response":"True"},
{"Title":"The Last Supper","Year":"1995","Rated":"R","Released":"05 Apr 1996","Runtime":"92 min","Genre":"Comedy, Crime, Drama","Director":"Stacy Title","Writer":"Dan Rosen (screenplay)","Actors":"Cameron Diaz, Ron Eldard, Annabeth Gish, Jonathan Penner","Plot":"Jude, Luke, Marc, Paulie and Pete are liberal-minded roommates and grad students at a Iowa post-secondary institution. Every Sunday for the past year, they have hosted a dinner party, inviting a friend over to have an open-minded discussion about whatever topics are of interest. On a dark and stormy night when Pete was supposed to bring a friend for one of those dinners, he instead comes home with Zachary Cody, who rescued a stranded Pete whose car broke down. They invite Zach to stay for dinner instead of Pete's missing friend. They soon find out that Zach is among other things a racist neo-Nazi, which brings up a potentially dangerous situation for Jewish Marc and black Luke. After some physical altercations and verbal threats, Marc ends up stabbing Zach dead out of what he considers self-defense. As the friends discuss what to do about Zach, they finally come to the conclusion that in killing Zach, they have done society a service. So they ponder 'why not invite other ultra-conservatives with extreme views to dinner to do the same to them'? Several dinner parties and deaths later, they think they've hit the jackpot when they meet powerful ultra-conservative broadcaster Norman Arbuthnot, who they invite for dinner. But the friends' plans start to unravel when they can't agree on whether certain of their guests deserve to die. It is also threatened by Sheriff Alice Stanley, who is not looking for the five's victims, but is nevertheless nosing around as she works on a missing girl case.","Language":"English","Country":"USA","Awards":"1 win & 1 nomination.","Poster":"N/A","Metascore":"N/A","imdbRating":"6.8","imdbVotes":"12,208","imdbID":"tt0113613","Type":"movie","Response":"True"},
{"Title":"Switched!","Year":"2003–2004","Rated":"N/A","Released":"26 May 2003","Runtime":"30 min","Genre":"Family","Director":"N/A","Writer":"N/A","Actors":"Cindy Oliver, Cody Oliver, James Oliver, Younger Oliver","Plot":"2 teens from different cities in the US are given a chance to swap lives to see how the other one lives.","Language":"English","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"6.6","imdbVotes":"49","imdbID":"tt0372727","Type":"series","totalSeasons":"2","Response":"True"},
{"Title":"Dastaan","Year":"2010–","Rated":"N/A","Released":"26 Jun 2010","Runtime":"N/A","Genre":"Drama","Director":"N/A","Writer":"N/A","Actors":"Sanam Baloch, Ahsan Khan, Fawad Khan, Saba amar","Plot":"Bano and her fiance face the trials and tribulations caused by the 1947 Indian partition.","Language":"Urdu","Country":"Pakistan","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BZTI4OWNhYTgtMjgwZi00MjE2LThiZTYtYTZkZDNkOGUxYTgyXkEyXkFcGdeXVyMzc0NzU5MTc@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.4","imdbVotes":"260","imdbID":"tt2404721","Type":"series","totalSeasons":"N/A","Response":"True"},
{"Title":"Les visiteurs","Year":"1993","Rated":"R","Released":"12 Jul 1996","Runtime":"107 min","Genre":"Comedy, Fantasy, Sci-Fi","Director":"Jean-Marie Poiré","Writer":"Christian Clavier, Jean-Marie Poiré","Actors":"Christian Clavier, Jean Reno, Valérie Lemercier, Marie-Anne Chazel","Plot":"A medieval nobleman and his suire are accidentally transported to contemporary times by a senile sorcerer. He enlists the aid of his descendent to try to find a way to return home, all the while trying to cope with the cultural and technological changes distinguishing his time from ours.","Language":"French, German, English","Country":"France","Awards":"1 win & 8 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjc2ODE2OTYtNTgyMS00ZDY1LWJiZjMtNzAxODcyN2VjZjhkXkEyXkFcGdeXVyMTY5MDE5NA@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.0","imdbVotes":"24,923","imdbID":"tt0108500","Type":"movie","Response":"True"},
{"Title":"Priyanka","Year":"1994","Rated":"N/A","Released":"N/A","Runtime":"N/A","Genre":"N/A","Director":"N/A","Writer":"N/A","Actors":"Anuradha Hasan, Radha Ravi, Arvind Swamy","Plot":"In the Southern part of India, there are two communities living - separated by caste and hatred of each other. The lower caste community has a young woman named Priyanka, who would like to ...","Language":"Tamil, Hindi","Country":"India","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"5.8","imdbVotes":"12","imdbID":"tt0318593","Type":"movie","Response":"True"},
{"Title":"Abhimanyu","Year":"1991","Rated":"N/A","Released":"N/A","Runtime":"140 min","Genre":"Crime, Drama, Musical","Director":"Priyadarshan","Writer":"T. Damodaran (screenplay)","Actors":"Mohanlal, Shankar Panicker, Geetha, Cochin Hanifa","Plot":"Hari (Mohanlal), a welder in a small factory, witnesses a gang-related murder and gets inadvertently involved with the underworld. The murder of a benevolent local boss complicates life in the slum where Hari lives, causing his slow transformation to a life of crime. Decent performances, in an otherwise weak script. Interesting perception of Bombay, which is consistently shown (and romanticized) in Malayalam films as being a hotbed of organized crime activity.","Language":"Malayalam","Country":"India","Awards":"1 win.","Poster":"N/A","Metascore":"N/A","imdbRating":"7.2","imdbVotes":"160","imdbID":"tt0092507","Type":"movie","Response":"True"},
{"Title":"Monchora","Year":"2016","Rated":"N/A","Released":"01 Jan 2016","Runtime":"135 min","Genre":"Drama, Romance","Director":"Sandip Ray","Writer":"Saradindu Bandopaddhyay (novel), Sandip Ray (screenplay)","Actors":"Paran Banerjee, Abir Chatterjee, Raima Sen, Saswata Chatterjee","Plot":"It's a romantic drama with colourful characters and hint of mystery typical of Saradindu Bandyopadhyay. The film revolves around the story of a thief played by Abir Chatterjee.","Language":"Bengali","Country":"India","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"8.9","imdbVotes":"7","imdbID":"tt5307382","Type":"movie","Response":"True"},
{"Title":"Reckless","Year":"2014","Rated":"N/A","Released":"29 Jun 2014","Runtime":"60 min","Genre":"Crime, Drama","Director":"N/A","Writer":"Dana Stevens","Actors":"Kim Wayans, Michael Gladis, Gregory Harrison, Anna Wood","Plot":"In sultry Charleston, where summer is long and secrets simmer behind every door, sex and crime walk hand in hand as two adversaries, a gorgeous Yankee litigator and a southern City Attorney, struggle to hide their intense attraction while clashing over a police sex scandal that threatens to implode the city.","Language":"English","Country":"USA","Awards":"2 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTk1MTU4MjI2NV5BMl5BanBnXkFtZTgwMTU0MTc3MDE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.2","imdbVotes":"2,813","imdbID":"tt2734804","Type":"series","totalSeasons":"1","Response":"True"},
{"Title":"Mysterion","Year":"1991","Rated":"N/A","Released":"30 Aug 1991","Runtime":"N/A","Genre":"Documentary","Director":"Pirjo Honkasalo, Eira Mollberg","Writer":"Pirjo Honkasalo (screenplay), Eira Mollberg (screenplay)","Actors":"N/A","Plot":"N/A","Language":"Finnish","Country":"Finland","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"4.9","imdbVotes":"12","imdbID":"tt0102498","Type":"movie","Response":"True"},
{"Title":"Kristo","Year":"1996","Rated":"N/A","Released":"01 Mar 1996","Runtime":"N/A","Genre":"Drama","Director":"Ben Yalung","Writer":"Emmanuel H. Borlaza (screenplay), Ruben Arthur Nicdao (screenplay), Ben Yalung (screenplay)","Actors":"Mat Ranillo III, Ruel Vernal, Conrad Poe, Edgar Mande","Plot":"N/A","Language":"Filipino, Tagalog","Country":"Philippines","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"7.3","imdbVotes":"7","imdbID":"tt0450790","Type":"movie","Response":"True"},
{"Title":"It Came from Somewhere Else","Year":"1988","Rated":"N/A","Released":"N/A","Runtime":"89 min","Genre":"Comedy, Sci-Fi","Director":"Howard Hassler","Writer":"Patrick V. Johnson (screenplay)","Actors":"William Vanarsdale, Don Aldrich, Robert Buckley, Allen M. Johnson","Plot":"Kung fu aliens from space have invaded the small town of Grand Bosh, accompanied by a surge of spontaneous human combustion and other mysterious phenomena in this awkward spoof of 50s sci-fi.","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMjE5NzYyNjgxM15BMl5BanBnXkFtZTcwNjczNDgyM@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"6.5","imdbVotes":"88","imdbID":"tt0238318","Type":"movie","Response":"True"},
{"Title":"Romeo and Juliet","Year":"1968","Rated":"PG","Released":"08 Oct 1968","Runtime":"138 min","Genre":"Drama, Romance","Director":"Franco Zeffirelli","Writer":"William Shakespeare (play), Franco Brusati (screenplay), Masolino D'Amico (screenplay), Franco Zeffirelli (screenplay)","Actors":"Leonard Whiting, Olivia Hussey, John McEnery, Milo O'Shea","Plot":"Shakespeare's classic tale of romance and tragedy. Two families of Verona, the Montagues and the Capulets, have been feuding with each other for years. Young Romeo Montague goes out with his friends to make trouble at a party the Capulets are hosting, but while there he spies the Capulet's daughter Juliet, and falls hopelessly in love with her. She returns his affections, but they both know that their families will never allow them to follow their hearts.","Language":"English","Country":"UK, Italy","Awards":"Won 2 Oscars. Another 14 wins & 15 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTkyMjIzOTcwOF5BMl5BanBnXkFtZTgwNzk2NjYxMTE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.7","imdbVotes":"23,734","imdbID":"tt0063518","Type":"movie","Response":"True"},
{"Title":"Inuyasha the Movie: Affections Touching Across Time","Year":"2001","Rated":"N/A","Released":"25 May 2005","Runtime":"100 min","Genre":"Animation, Action, Adventure","Director":"Toshiya Shinohara","Writer":"Rumiko Takahashi (comic book), Katsuyuki Sumizawa (screenplay)","Actors":"Kappei Yamaguchi, Satsuki Yukino, Kôji Tsujitani, Houko Kuwashima","Plot":"InuYasha is a half-demon who was trapped in the Legendary Tree and was set free by Kagome, a girl who traveled 500 years through time. This time, both of them will have to face Menomaru, a Chinese demon whose father, known as Hyoga, came 300 years ago to invade Japan, but was stopped by InuYasha's Father. InuYasha and Kagome, along with Sango, Miroku, Shippou, Kaede and Myoga, will try to stop Menomaru in his becoming the most powerful demon ever.","Language":"Japanese, English","Country":"Japan","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMT1MTI3MzA0Ml5BMl5BanBnXkFtZTcwOTY3MTcyM@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.4","imdbVotes":"1,543","imdbID":"tt0322645","Type":"movie","Response":"True"},
{"Title":"Love Me or Leave Me","Year":"1955","Rated":"PASSED","Released":"10 Jun 1955","Runtime":"122 min","Genre":"Biography, Drama, Music","Director":"Charles Vidor","Writer":"Daniel Fuchs (screenplay), Isobel Lennart (screenplay), Daniel Fuchs (story)","Actors":"Doris Day, James Cagney, Cameron Mitchell, Robert Keith","Plot":"In 1920's Chicago, Ruth Etting wants to be a renowned singer, which is a far step away from her current work as a taxi dancer. Upon walking into the dance hall and seeing her, Chicago gangster Marty Snyder immediately falls for Ruth, and works toward being her lover, which he believes he can achieve by opening up singing opportunities for her. Ruth is initially wary of Marty, but makes it clear that she is not interested in him in a romantic sense. Regardless, he does help her professionally, and through his opportunities, which are achieved through intimidation and fear, Ruth does uickly start to gain a name as a singer, which she is able to do because of her talent and despite Marty's intimidation tactics. However, the greater her success, the more reliant she becomes on him. This becomes an issue in their relationship as she believes he can take her only so far before he becomes a liability, however he will never let her go that easily. The one person who tried and tries to get Ruth away from her unhappy life with Marty is Johnny Alderman, the musical advisor Marty hired for Ruth at the first gig he got for her, and who also loves Ruth himself.","Language":"English","Country":"USA","Awards":"Won 1 Oscar. Another 1 win & 6 nominations.","Poster":"N/A","Metascore":"N/A","imdbRating":"7.2","imdbVotes":"2,736","imdbID":"tt0048317","Type":"movie","Response":"True"},
{"Title":"The Lollipop Generation","Year":"2008","Rated":"N/A","Released":"03 Apr 2008","Runtime":"75 min","Genre":"Drama","Director":"G.B. Jones","Writer":"G.B. Jones","Actors":"Helen Bed, Anonymous Boy, Andrew Cecil, Torry Colichio","Plot":"N/A","Language":"English","Country":"Canada","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"7.2","imdbVotes":"6","imdbID":"tt1512506","Type":"movie","Response":"True"},
{"Title":"Captain Kishore","Year":"1957","Rated":"N/A","Released":"N/A","Runtime":"N/A","Genre":"Action, Thriller","Director":"J.B.H. Wadia","Writer":"N/A","Actors":"Suresh, Vijaya Choudhury, Shashikala, Anwar Hussain","Plot":"N/A","Language":"Hindi","Country":"India","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt0386366","Type":"movie","Response":"True"},
{"Title":"Babu Bangaram","Year":"2016","Rated":"N/A","Released":"12 Aug 2016","Runtime":"150 min","Genre":"Action, Comedy","Director":"Maruthi Dasari","Writer":"N/A","Actors":"Venkatesh Daggubati, Vennela Kishore, Nayanthara","Plot":"A cop goes undercover to investigate a businesswoman and her father.","Language":"Telugu","Country":"India","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BYTUxM2NiNzAtNWwMy00MWE1LThjNjktYWFjNDYxZGNhZDI3XkEyXkFcGdeXVyNTA5Mzg4NzE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.1","imdbVotes":"45","imdbID":"tt5953594","Type":"movie","Response":"True"},
{"Title":"Passenger Side","Year":"2009","Rated":"N/A","Released":"01 Apr 2011","Runtime":"85 min","Genre":"Comedy, Drama","Director":"Matt Bissonnette","Writer":"Matt Bissonnette","Actors":"Adam Scott, Joel Bissonnette, Richard Medina, Mickey Cottrell","Plot":"Michael Brown's birthday begins with a telephone call from his estranged, drug addicted brother Tobey. Tobey is totally unaware that it is his older brother's birthday, but he is very aware that his car is broken, and he begs Michael to drive him on various apparently legitimate, vital errands. As Bruce Springsteen has astutely noted, \"a man who turns his back on his family just ain't no good\". So Michael puts off his seemingly romantic birthday plans, and with his brother embarks on a sketchy, meandering day long odyssey though the mysteries of Los Angeles County. As the day wears on, it becomes clear that this drive will lead them to some very unexpected destinations.","Language":"English, Spanish","Country":"Canada","Awards":"1 nomination.","Poster":"http://ia.media-imdb.com/images/M/MV5BMT0NTMwMTk5MV5BMl5BanBnXkFtZTcwMDI1OTg4Mg@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"6.0","imdbVotes":"739","imdbID":"tt1227170","Type":"movie","Response":"True"},
{"Title":"Skin Deep","Year":"1989","Rated":"R","Released":"10 Mar 1989","Runtime":"97 min","Genre":"Comedy, Drama, Romance","Director":"Blake Edwards","Writer":"Blake Edwards","Actors":"John Ritter, Vincent Gardenia, Alyson Reed, Joel Brooks","Plot":"Zach Hutton is a womanizing, drunken, allelic writer whose life seems to be falling apart at the seams. He's still in love with his ex-wife (whose family can't stand him), writer's block is keeping him from completing his latest novel, and he repeatedly finds himself in trouble of one sort or another with the law, ex-girlfriends, and jealous boyfriends.","Language":"English","Country":"USA","Awards":"N/A","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjE0MTk3ODUyOV5BMl5BanBnXkFtZTcwNTUyNDkxM@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"6.1","imdbVotes":"3,159","imdbID":"tt0098343","Type":"movie","Response":"True"},
{"Title":"Gulliver's Travels","Year":"2010","Rated":"PG","Released":"25 Dec 2010","Runtime":"85 min","Genre":"Adventure, Comedy, Family","Director":"Rob Letterman","Writer":"Joe Stillman (screenplay), Nicholas Stoller (screenplay), Jonathan Swift (book)","Actors":"Jack Black, Jason Segel, Emily Blunt, Amanda Peet","Plot":"Lemuel Gulliver has been working in the mail room of a New York daily newspaper for the past ten years. Afraid to put himself out there, he considers himself a loser, as do all his peers. One day, after having finally had enough, he decides to declare his flame to the beautiful Darcy Silverman, the newspaper's travel editor and one of Gulliver's only friends...only to chicken out at the last minute and instead tell her that he'd like to try his hand at writing a column. Darcy accepts and sends him on an assignment to the Bermuda Triangle. There, Gulliver becomes shipwrecked and ends up on the island of Liliput, where he is twelve taller than the tallest man. For the first time, Gulliver has people looking up to him...","Language":"English","Country":"USA","Awards":"3 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTU0NTUwOTM3Nl5BMl5BanBnXkFtZTcwMDA3NjIwNA@@._V1_SX300.jpg","Metascore":"33","imdbRating":"4.9","imdbVotes":"53,644","imdbID":"tt1320261","Type":"movie","Response":"True"},
{"Title":"Nude Nuns with Big Guns","Year":"2010","Rated":"NOT RATED","Released":"24 Sep 2010","Runtime":"91 min","Genre":"Action, Comedy, Thriller","Director":"Joseph Guzman","Writer":"Joseph Guzman, Robert James Hayes II","Actors":"Asun Ortega, David Castro, Perry D'Marco, Maxie Santillan Jr.","Plot":"Upon taking her vows to become a nun, Sister Sarah is abused, brainwashed and drugged into submission by the corrupt clergy. On the verge of death from a lethal dose of drugs, Sister Sarah receives a message from GOD telling her to take vengeance on all those who did her wrong. Armed with God's will and an arsenal of big guns, she dispenses Judgment Day on her former tormentors. When the church hires the merciless motorcycle gang the \"Los Muertos\" to track down and kill her they soon realize that this SISTER IS ONE BAD MOTHER.","Language":"English","Country":"USA","Awards":"N/A","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyNzMzMTUzNl5BMl5BanBnXkFtZTcwMTUyNDMyNA@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"3.9","imdbVotes":"4,714","imdbID":"tt1352388","Type":"movie","Response":"True"},
{"Title":"Monty","Year":"1994–","Rated":"N/A","Released":"11 Jan 1994","Runtime":"30 min","Genre":"Comedy, Talk-Show","Director":"N/A","Writer":"Marc Lawrence","Actors":"Henry Winkler, Kate Burton, David Schwimmer, David Krumholtz","Plot":"Monty Richardson is a Conservative talk-show host, a la Rush Limbaugh. His family, however, are rather liberal, including his son's radically left-wing girlfriend. The comedy starts as they try to resolve their differences...","Language":"English","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"4.2","imdbVotes":"29","imdbID":"tt0108863","Type":"series","totalSeasons":"1","Response":"True"},
{"Title":"Fashion Model","Year":"1945","Rated":"N/A","Released":"02 Mar 1945","Runtime":"61 min","Genre":"Comedy, Mystery","Director":"William Beaudine","Writer":"Tim Ryan (screenplay), Victor Hammond (screenplay), Victor Hammond (original story)","Actors":"Robert Lowery, Marjorie Weaver, Tim Ryan, Lorna Gray","Plot":"Peggy Rooney, Yvonne Brewster, and Marie Lewis are models at Madame Celeste's fashion house, Madame Celeste who is only the front for the business' true designer and owner, her ex-husband, Jacues Duval. There is disharmony at the fashion house, as Yvonne is trying to steal Peggy's boyfriend, Jimmy O'Brien, Madame Celeste's stock clerk and driver. This behavior is typical for Yvonne as she was the cause of Duval and Celeste's marriage breaking up. Jimmy is implicated as the culprit when Yvonne is found strangled to death, as Mac, the security guard, overheard Jimmy state that he would strangle Yvonne. In reality, Jimmy said that to Peggy in jest to appease her jealousy. Beyond all the employees at the fashion house, other people who are brought in for uestioning by the police are: Mr. Davis, Yvonne's older wealthy boyfriend; and snobbish and condescending customer Jessica Van Allen and her henpecked husband Harvey Van Allen, the last two customers in the store before closing when Yvonne was murdered. All the models detest Mrs. Van Allen, who they criticized to her face on that last visit. Despite their issues, Peggy is certain Jimmy did not kill Yvonne. As Jimmy and Peggy try to clear Jimmy's name by finding the real killer, they come to believe Yvonne's death has something to do with an expensive diamond brooch Davis bought for Yvonne. But as they progress in their investigation, Peggy and Jimmy come across one dead body after another, which further implicates Peggy as Jimmy's accomplice. Their only hope is that Marie can remember the name of the man Yvonne muttered shortly before her murder. But the closer they get to the truth, the more their own lives are in danger at the hands of the killer.","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMTYyMjkwMDg0NF5BMl5BanBnXkFtZTgwNDUyNzk1MDE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"5.0","imdbVotes":"101","imdbID":"tt0037692","Type":"movie","Response":"True"},
{"Title":"Carnival","Year":"1946","Rated":"APPROVED","Released":"02 Dec 1946","Runtime":"93 min","Genre":"Romance","Director":"Stanley Haynes","Writer":"Guy Green (screen adaptation), Stanley Haynes (screen adaptation), Compton MacKenzie (novel), Peter Ustinov (additional dialogue)","Actors":"Sally Gray, Michael Wilding, Stanley Holloway, Bernard Miles","Plot":"N/A","Language":"English","Country":"UK","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"6.2","imdbVotes":"51","imdbID":"tt0038398","Type":"movie","Response":"True"},
{"Title":"Dunia","Year":"1946","Rated":"N/A","Released":"01 Sep 1946","Runtime":"N/A","Genre":"N/A","Director":"Mohammed Karim","Writer":"Mohammed Karim (dialogue), Mohammed Karim (script)","Actors":"Dawlad Abiad, Faten Hamama, Raiya Ibrahim, Suleiman Naguib","Plot":"N/A","Language":"Arabic","Country":"Egypt","Awards":"1 nomination.","Poster":"N/A","Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt0285527","Type":"movie","Response":"True"},
{"Title":"The Divided Trail: A Native American Odyssey","Year":"1977","Rated":"N/A","Released":"01 Oct 1977","Runtime":"33 min","Genre":"Documentary, Short","Director":"Jerry Aronson","Writer":"N/A","Actors":"N/A","Plot":"N/A","Language":"English","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"6.2","imdbVotes":"12","imdbID":"tt0077442","Type":"movie","Response":"True"},
{"Title":"New Port South","Year":"2001","Rated":"PG-13","Released":"07 Sep 2001","Runtime":"95 min","Genre":"Drama","Director":"Kyle Cooper","Writer":"James Hughes","Actors":"Blake Shields, Will Estes, Kevin Christy, Melissa George","Plot":"A cranky high school student cons his friends into helping him with a propaganda blitz against the school administration which results in a student body riot and the inevitable moral lesson... all set to a trance-hop soundtrack.","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMTczMzI3MjYyMl5BMl5BanBnXkFtZTcwODUwMjyM@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"4.9","imdbVotes":"457","imdbID":"tt0229003","Type":"movie","Response":"True"},
{"Title":"Stand Up and Cheer!","Year":"1934","Rated":"PASSED","Released":"04 May 1934","Runtime":"68 min","Genre":"Comedy, Musical","Director":"Hamilton MacFadden","Writer":"Lew Brown (story and dialogue: collaborator), Will Rogers (story idea suggested), Philip Klein (story idea suggested), Ralph Spence (dialogue)","Actors":"Warner Baxter, Madge Evans, James Dunn, Sylvia Froos","Plot":"President Franklin Roosevelt appoints a theatrical producer as the new Secretary of Amusement in order to cheer up an American public still suffering through the Depression. The new secretary soon runs afoul of political lobbyists out to destroy his department.","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMjIyNTg5Mj2Nl5BMl5BanBnXkFtZTgwMTyMjk5MzE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"5.7","imdbVotes":"319","imdbID":"tt0025829","Type":"movie","Response":"True"},
{"Title":"Barfly","Year":"1987","Rated":"R","Released":"16 Oct 1987","Runtime":"100 min","Genre":"Comedy, Drama, Romance","Director":"Barbet Schroeder","Writer":"Charles Bukowski","Actors":"Mickey Rourke, Faye Dunaway, Alice Krige, Jack Nance","Plot":"Henry Chinaski never cared for the American dream, the thought of needing to become 'something' and fit into the system disgusts him. He believes that life is free and yours to live like you see fit, and if that in some cases involves copious amounts of whiskey then so be it. Henry spends his days drinking and listening to the radio, and he spends his nights drinking and fighting against Eddy who he thinks personifies shallowness and shameless self promoting. Sometimes in the middle of this he finds the time to jot down a few lines of poetry or a short story. After fighting Eddy and winning for a change Henry is thrown out of his regular bar where Eddy is a bartender. This leads him to seek another watering hole where he happens to find Wanda who is a barfly, in her own words \"if another man came along with a fifth of whiskey, I'd go with him\". Henry is not fazed by this thou and moves in with her. Of course Wanda immediately goes off and sleeps with Eddy, but after some clothes throwing and two visits from the paramedics Henry and Wanda manage to patch up their relationship. Then Henry gets a visit from a literary agent who has decided to publish one of his stories that he sent in because he \"liked the name of the mag\". He follows the agent home to her place in order to receive his payment and with the help of a little whiskey sleeps with her. When he leaves to go back to the bar and back to Wanda the agent is heartbroken, she sees something special in Henry and has fallen in love with him. She follows him to his usual bar and gets into a cat fight with Wanda that Wanda wins. In celebration of new found love, happiness and money Henry buys a round for everyone at the bar and toasts them \"to my friends!\"","Language":"English","Country":"USA","Awards":"Nominated for 1 Golden Globe. Another 3 nominations.","Poster":"N/A","Metascore":"N/A","imdbRating":"7.3","imdbVotes":"14,512","imdbID":"tt0092618","Type":"movie","Response":"True"}
        ]
        movieData.sort((a, b) => a.Title < b.Title?-1:1)
        this.setState({movieData: movieData})
    }

    addMovieHandler = (movie) => {
        let updatedMovieDataSet = [movie,...this.state.movieData]

        console.log(movie)

        this.setState({movieData: updatedMovieDataSet})
    }

    updatePlotHandler = (plot) => {
        
        let movieId = plot.plotId;
        let updatedPlot = plot.plot;

        if(movieId.length > 0 && updatedPlot.length > 0)
        {
            let updatedMovieDataSet = [...this.state.movieData]

            updatedMovieDataSet.find(record => record.imdbID.toUpperCase() === movieId).Plot = updatedPlot
    
            this.setState({movieData: updatedMovieDataSet})
        }
    }

    deleteHandler(movieId) {
        const result = this.state.movieData.filter(record => record.imdbID !== movieId)
        this.setState({movieData: result});
    }

    onChangeSearch = (event) => 
    {
        this.setState({search: event.target.value});
    }

    handleSort = (colName) => {

        let sorted = [...this.state.movieData]
        let prevCount = this.state.countTableSortClick

        this.setState({countTableSortClick: ++prevCount})

        if(this.state.countTableSortClick % 2 === 0)
        {
            sorted.sort((a, b) => a[colName] < b[colName]?1:-1)
        }
        else {
            sorted.sort((a, b) => a[colName] < b[colName]?-1:1)
        }
        this.setState({movieData: sorted})
    }

    render()
    {
        // filter by movie name, genre or year
        let filterableMovies = this.state.movieData.filter(movie => 
            movie.Title.toLowerCase()
            .includes(this.state.search.toLowerCase()) || 
            movie.Genre.toLowerCase()
            .includes(this.state.search.toLowerCase()) || 
            movie.Year.toLowerCase()
            .includes(this.state.search.toLowerCase()))

        return (            
        <div className="DisplayMovieRecordsStyle">
            <AddMovieModalBox 
            text="Add Movie" 
            addMovie={movie => this.addMovieHandler(movie)}
            />
            <InputBoxes 
            filterSearch={this.onChangeSearch} 
            value={this.state.search}
            />
            <MovieTable movies={filterableMovies} 
            onSubmitPlot={plot => this.updatePlotHandler(plot)} 
            remove={this.deleteHandler.bind(this)} 
            sortMyTable={this.handleSort}
            />
        </div>
        )
    }
}
